-- ===========================================
-- 売上データINSERT Task（1時間毎）
-- 1年前の同日・同時間帯データを今日のデータとしてコピー
-- ===========================================
CREATE OR REPLACE TASK FOODEX_DEMO.BUYER_AGENT.TASK_INSERT_SALES_DATA
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  SCHEDULE = '1 HOUR'
  COMMENT = '1年前の同日・同時間帯データを今日のデータとしてINSERT'
AS
INSERT INTO FOODEX_DEMO.BUYER_AGENT.ID_POS_TRANSACTIONS
WITH max_id AS (
    SELECT COALESCE(MAX(CAST(SUBSTR(TRANSACTION_ID, 2) AS INT)), 0) AS max_num
    FROM FOODEX_DEMO.BUYER_AGENT.ID_POS_TRANSACTIONS
),
year_ago_data AS (
    SELECT *
    FROM FOODEX_DEMO.BUYER_AGENT.ID_POS_TRANSACTIONS
    WHERE TRANSACTION_DATE = DATEADD('YEAR', -1, CURRENT_DATE())
      AND TRANSACTION_TIME BETWEEN TIMEADD('HOUR', -1, CURRENT_TIME()) AND CURRENT_TIME()
)
SELECT
    'T' || LPAD((m.max_num + ROW_NUMBER() OVER (ORDER BY y.TRANSACTION_TIME))::VARCHAR, 9, '0') AS TRANSACTION_ID,
    y.BASKET_ID,
    CURRENT_DATE() AS TRANSACTION_DATE,
    y.TRANSACTION_TIME,
    y.CUSTOMER_ID,
    y.STORE_ID,
    y.PRODUCT_ID,
    y.QUANTITY,
    y.UNIT_SELLING_PRICE,
    y.DISCOUNT_AMOUNT,
    y.SALES_AMOUNT,
    DECODE(DAYOFWEEK(CURRENT_DATE()), 0,'日',1,'月',2,'火',3,'水',4,'木',5,'金',6,'土') AS DAY_OF_WEEK
FROM year_ago_data y
CROSS JOIN max_id m;

-- ===========================================
-- 在庫データ洗い替え Task（毎日AM6時）
-- 最新の在庫データを今日の日付で洗い替え
-- ===========================================
CREATE OR REPLACE TASK FOODEX_DEMO.BUYER_AGENT.TASK_INSERT_INVENTORY_DATA
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  SCHEDULE = 'USING CRON 0 6 * * * Asia/Tokyo'
  COMMENT = '最新の在庫データを今日の日付で洗い替え'
AS
BEGIN
    DELETE FROM FOODEX_DEMO.BUYER_AGENT.INVENTORY
    WHERE INVENTORY_DATE = CURRENT_DATE();

    INSERT INTO FOODEX_DEMO.BUYER_AGENT.INVENTORY
    SELECT
        CURRENT_DATE() AS INVENTORY_DATE,
        STORE_ID,
        PRODUCT_ID,
        STOCK_QUANTITY,
        REORDER_POINT,
        SAFETY_STOCK,
        DAYS_OF_SUPPLY,
        LAST_REPLENISHMENT_DATE
    FROM FOODEX_DEMO.BUYER_AGENT.INVENTORY
    WHERE INVENTORY_DATE = (SELECT MAX(INVENTORY_DATE) FROM FOODEX_DEMO.BUYER_AGENT.INVENTORY WHERE INVENTORY_DATE < CURRENT_DATE());
END;

-- ===========================================
-- Taskの有効化（必要に応じて実行）
-- ===========================================
-- ALTER TASK FOODEX_DEMO.BUYER_AGENT.TASK_INSERT_SALES_DATA RESUME;
-- ALTER TASK FOODEX_DEMO.BUYER_AGENT.TASK_INSERT_INVENTORY_DATA RESUME;

-- ===========================================
-- Task確認用クエリ
-- ===========================================
-- SHOW TASKS IN FOODEX_DEMO.BUYER_AGENT;
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) ORDER BY SCHEDULED_TIME DESC LIMIT 10;



select * from FOODEX_DEMO.BUYER_AGENT.ID_POS_TRANSACTIONS
where basket_id = 'B00025399';
order by TRANSACTION_DATE desc;



select * from FOODEX_DEMO.BUYER_AGENT.ID_POS_TRANSACTIONS
where TRANSACTION_ID = 'T000101380';
order by TRANSACTION_DATE desc;