-- ============================================================
-- Foodex Buyer Agent Demo - Table DDL
-- ============================================================

USE DATABASE FOODEX_DEMO;
USE SCHEMA BUYER_AGENT;

-- 商品マスタ
CREATE OR REPLACE TABLE PRODUCT_MASTER (
    PRODUCT_ID        VARCHAR(10)   NOT NULL PRIMARY KEY,
    JAN_CODE          VARCHAR(13),
    PRODUCT_NAME      VARCHAR(200)  NOT NULL,
    BRAND_NAME        VARCHAR(100),
    MANUFACTURER_NAME VARCHAR(100)  NOT NULL,
    CATEGORY_LARGE    VARCHAR(50)   NOT NULL,
    CATEGORY_MEDIUM   VARCHAR(50),
    CATEGORY_SMALL    VARCHAR(50),
    UNIT_PRICE        NUMBER(10,0),
    COST_PRICE        NUMBER(10,0),
    UNIT_VOLUME       VARCHAR(20),
    UNIT_MEASURE      VARCHAR(10),
    LAUNCH_DATE       DATE,
    PRODUCT_DESCRIPTION VARCHAR(500),
    IS_NEW_PRODUCT    BOOLEAN DEFAULT FALSE
);

-- 顧客マスタ
CREATE OR REPLACE TABLE CUSTOMER_MASTER (
    CUSTOMER_ID       VARCHAR(10)   NOT NULL PRIMARY KEY,
    GENDER            VARCHAR(4),
    BIRTH_DATE        DATE,
    AGE_GROUP         VARCHAR(10),
    PREFECTURE        VARCHAR(10),
    CITY              VARCHAR(50),
    MEMBERSHIP_TIER   VARCHAR(20),
    REGISTRATION_DATE DATE,
    FAMILY_SIZE       NUMBER(2,0),
    HAS_CHILDREN      BOOLEAN,
    OCCUPATION        VARCHAR(30)
);

-- 店舗マスタ
CREATE OR REPLACE TABLE STORE_MASTER (
    STORE_ID          VARCHAR(5)    NOT NULL PRIMARY KEY,
    STORE_NAME        VARCHAR(100)  NOT NULL,
    PREFECTURE        VARCHAR(10),
    CITY              VARCHAR(50),
    STORE_FORMAT      VARCHAR(20),
    SALES_FLOOR_AREA  NUMBER(8,0),
    OPENING_DATE      DATE
);

-- ID-POSトランザクション
CREATE OR REPLACE TABLE ID_POS_TRANSACTIONS (
    TRANSACTION_ID     VARCHAR(20)  NOT NULL PRIMARY KEY,
    BASKET_ID          VARCHAR(20)  NOT NULL,
    TRANSACTION_DATE   DATE         NOT NULL,
    TRANSACTION_TIME   TIME,
    CUSTOMER_ID        VARCHAR(10)  NOT NULL,
    STORE_ID           VARCHAR(5)   NOT NULL,
    PRODUCT_ID         VARCHAR(10)  NOT NULL,
    QUANTITY           NUMBER(5,0)  DEFAULT 1,
    UNIT_SELLING_PRICE NUMBER(10,0),
    DISCOUNT_AMOUNT    NUMBER(10,0) DEFAULT 0,
    SALES_AMOUNT       NUMBER(10,0),
    DAY_OF_WEEK        VARCHAR(3),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_MASTER(CUSTOMER_ID),
    FOREIGN KEY (STORE_ID)    REFERENCES STORE_MASTER(STORE_ID),
    FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT_MASTER(PRODUCT_ID)
);

-- 在庫データ
CREATE OR REPLACE TABLE INVENTORY (
    INVENTORY_DATE          DATE        NOT NULL,
    STORE_ID                VARCHAR(5)  NOT NULL,
    PRODUCT_ID              VARCHAR(10) NOT NULL,
    STOCK_QUANTITY          NUMBER(8,0),
    REORDER_POINT           NUMBER(8,0),
    SAFETY_STOCK            NUMBER(8,0),
    DAYS_OF_SUPPLY          NUMBER(5,1),
    LAST_REPLENISHMENT_DATE DATE,
    PRIMARY KEY (INVENTORY_DATE, STORE_ID, PRODUCT_ID),
    FOREIGN KEY (STORE_ID)    REFERENCES STORE_MASTER(STORE_ID),
    FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT_MASTER(PRODUCT_ID)
);
