-- ============================================================
-- Foodex Buyer Agent Demo - Data Loading
-- ============================================================

USE DATABASE FOODEX_DEMO;
USE SCHEMA BUYER_AGENT;

-- 店舗マスタのロード
COPY INTO STORE_MASTER
FROM @FOODEX_DATA_STAGE/store_master
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    ENCODING = 'UTF8'
)
ON_ERROR = 'CONTINUE';

-- 商品マスタのロード
COPY INTO PRODUCT_MASTER
FROM @FOODEX_DATA_STAGE/product_master
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    ENCODING = 'UTF8'
)
ON_ERROR = 'CONTINUE';

-- 顧客マスタのロード
COPY INTO CUSTOMER_MASTER
FROM @FOODEX_DATA_STAGE/customer_master
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    ENCODING = 'UTF8'
)
ON_ERROR = 'CONTINUE';

-- ID-POSトランザクションのロード
COPY INTO ID_POS_TRANSACTIONS
FROM @FOODEX_DATA_STAGE/id_pos_transactions
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    ENCODING = 'UTF8'
)
ON_ERROR = 'CONTINUE';

-- 在庫データのロード
COPY INTO INVENTORY
FROM @FOODEX_DATA_STAGE/inventory
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    ENCODING = 'UTF8'
)
ON_ERROR = 'CONTINUE';

-- ロード結果確認
SELECT 'PRODUCT_MASTER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM PRODUCT_MASTER
UNION ALL
SELECT 'CUSTOMER_MASTER', COUNT(*) FROM CUSTOMER_MASTER
UNION ALL
SELECT 'STORE_MASTER', COUNT(*) FROM STORE_MASTER
UNION ALL
SELECT 'ID_POS_TRANSACTIONS', COUNT(*) FROM ID_POS_TRANSACTIONS
UNION ALL
SELECT 'INVENTORY', COUNT(*) FROM INVENTORY;
