-- ============================================================
-- Foodex Buyer Agent Demo - Analytical Views
-- ============================================================

USE DATABASE FOODEX_DEMO;
USE SCHEMA BUYER_AGENT;

-- ============================================================
-- 1. 商品別売上サマリ
-- ============================================================
CREATE OR REPLACE VIEW V_PRODUCT_SALES_SUMMARY AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.BRAND_NAME,
    p.MANUFACTURER_NAME,
    p.CATEGORY_LARGE,
    p.CATEGORY_MEDIUM,
    p.CATEGORY_SMALL,
    p.UNIT_PRICE,
    p.COST_PRICE,
    p.IS_NEW_PRODUCT,
    DATE_TRUNC('MONTH', t.TRANSACTION_DATE) AS SALES_MONTH,
    COUNT(DISTINCT t.BASKET_ID)             AS BASKET_COUNT,
    COUNT(t.TRANSACTION_ID)                 AS TRANSACTION_COUNT,
    SUM(t.QUANTITY)                         AS TOTAL_QUANTITY,
    SUM(t.SALES_AMOUNT)                     AS TOTAL_SALES,
    SUM(t.DISCOUNT_AMOUNT * t.QUANTITY)     AS TOTAL_DISCOUNT,
    ROUND(SUM(t.SALES_AMOUNT) / NULLIF(SUM(t.QUANTITY), 0), 0) AS AVG_SELLING_PRICE,
    ROUND(
        (SUM(t.SALES_AMOUNT) - SUM(t.QUANTITY) * p.COST_PRICE)
        / NULLIF(SUM(t.SALES_AMOUNT), 0) * 100, 1
    ) AS GROSS_MARGIN_PCT
FROM ID_POS_TRANSACTIONS t
JOIN PRODUCT_MASTER p ON t.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID, p.PRODUCT_NAME, p.BRAND_NAME, p.MANUFACTURER_NAME,
    p.CATEGORY_LARGE, p.CATEGORY_MEDIUM, p.CATEGORY_SMALL,
    p.UNIT_PRICE, p.COST_PRICE, p.IS_NEW_PRODUCT,
    DATE_TRUNC('MONTH', t.TRANSACTION_DATE);

-- ============================================================
-- 2. 併売分析ビュー（商品ペア）
-- ============================================================
CREATE OR REPLACE VIEW V_BASKET_ANALYSIS AS
WITH basket_items AS (
    SELECT DISTINCT
        t.BASKET_ID,
        t.PRODUCT_ID,
        p.PRODUCT_NAME,
        p.CATEGORY_LARGE,
        p.BRAND_NAME
    FROM ID_POS_TRANSACTIONS t
    JOIN PRODUCT_MASTER p ON t.PRODUCT_ID = p.PRODUCT_ID
)
SELECT
    a.PRODUCT_ID    AS PRODUCT_A_ID,
    a.PRODUCT_NAME  AS PRODUCT_A_NAME,
    a.CATEGORY_LARGE AS PRODUCT_A_CATEGORY,
    b.PRODUCT_ID    AS PRODUCT_B_ID,
    b.PRODUCT_NAME  AS PRODUCT_B_NAME,
    b.CATEGORY_LARGE AS PRODUCT_B_CATEGORY,
    COUNT(DISTINCT a.BASKET_ID) AS CO_OCCURRENCE_COUNT,
    ROUND(
        COUNT(DISTINCT a.BASKET_ID) * 1.0
        / NULLIF((SELECT COUNT(DISTINCT BASKET_ID) FROM basket_items WHERE PRODUCT_ID = a.PRODUCT_ID), 0)
        * 100, 2
    ) AS CONFIDENCE_A_TO_B_PCT,
    ROUND(
        COUNT(DISTINCT a.BASKET_ID) * 1.0
        / NULLIF((SELECT COUNT(DISTINCT BASKET_ID) FROM basket_items WHERE PRODUCT_ID = b.PRODUCT_ID), 0)
        * 100, 2
    ) AS CONFIDENCE_B_TO_A_PCT
FROM basket_items a
JOIN basket_items b
    ON a.BASKET_ID = b.BASKET_ID
    AND a.PRODUCT_ID < b.PRODUCT_ID
GROUP BY
    a.PRODUCT_ID, a.PRODUCT_NAME, a.CATEGORY_LARGE,
    b.PRODUCT_ID, b.PRODUCT_NAME, b.CATEGORY_LARGE
HAVING COUNT(DISTINCT a.BASKET_ID) >= 5;

-- ============================================================
-- 3. 顧客購買プロファイル
-- ============================================================
CREATE OR REPLACE VIEW V_CUSTOMER_PURCHASE_PROFILE AS
SELECT
    c.CUSTOMER_ID,
    c.GENDER,
    c.AGE_GROUP,
    c.PREFECTURE,
    c.MEMBERSHIP_TIER,
    c.FAMILY_SIZE,
    c.HAS_CHILDREN,
    c.OCCUPATION,
    COUNT(DISTINCT t.BASKET_ID)             AS VISIT_COUNT,
    COUNT(t.TRANSACTION_ID)                 AS TOTAL_ITEMS_PURCHASED,
    SUM(t.SALES_AMOUNT)                     AS TOTAL_SPEND,
    ROUND(SUM(t.SALES_AMOUNT) / NULLIF(COUNT(DISTINCT t.BASKET_ID), 0), 0) AS AVG_BASKET_VALUE,
    MIN(t.TRANSACTION_DATE)                 AS FIRST_PURCHASE_DATE,
    MAX(t.TRANSACTION_DATE)                 AS LAST_PURCHASE_DATE,
    DATEDIFF('day', MIN(t.TRANSACTION_DATE), MAX(t.TRANSACTION_DATE)) AS ACTIVE_DAYS,
    COUNT(DISTINCT p.CATEGORY_LARGE)        AS CATEGORY_BREADTH,
    MODE(p.CATEGORY_LARGE)                  AS MOST_PURCHASED_CATEGORY
FROM CUSTOMER_MASTER c
JOIN ID_POS_TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
JOIN PRODUCT_MASTER p ON t.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    c.CUSTOMER_ID, c.GENDER, c.AGE_GROUP, c.PREFECTURE,
    c.MEMBERSHIP_TIER, c.FAMILY_SIZE, c.HAS_CHILDREN, c.OCCUPATION;

-- ============================================================
-- 4. 新商品パフォーマンス追跡
-- ============================================================
CREATE OR REPLACE VIEW V_NEW_PRODUCT_PERFORMANCE AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.BRAND_NAME,
    p.MANUFACTURER_NAME,
    p.CATEGORY_LARGE,
    p.CATEGORY_MEDIUM,
    p.UNIT_PRICE,
    p.COST_PRICE,
    p.LAUNCH_DATE,
    DATEDIFF('day', p.LAUNCH_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAUNCH,
    t.TRANSACTION_DATE,
    DATEDIFF('day', p.LAUNCH_DATE, t.TRANSACTION_DATE) AS DAYS_AFTER_LAUNCH,
    COUNT(t.TRANSACTION_ID)       AS DAILY_TRANSACTIONS,
    SUM(t.QUANTITY)               AS DAILY_QUANTITY,
    SUM(t.SALES_AMOUNT)           AS DAILY_SALES,
    COUNT(DISTINCT t.CUSTOMER_ID) AS DAILY_UNIQUE_BUYERS,
    COUNT(DISTINCT t.STORE_ID)    AS DAILY_SELLING_STORES
FROM PRODUCT_MASTER p
JOIN ID_POS_TRANSACTIONS t ON p.PRODUCT_ID = t.PRODUCT_ID
WHERE p.IS_NEW_PRODUCT = TRUE
GROUP BY
    p.PRODUCT_ID, p.PRODUCT_NAME, p.BRAND_NAME, p.MANUFACTURER_NAME,
    p.CATEGORY_LARGE, p.CATEGORY_MEDIUM, p.UNIT_PRICE, p.COST_PRICE,
    p.LAUNCH_DATE, t.TRANSACTION_DATE;

-- ============================================================
-- 5. 在庫状況（欠品リスク分析）
-- ============================================================
CREATE OR REPLACE VIEW V_INVENTORY_STATUS AS
WITH recent_sales AS (
    SELECT
        STORE_ID,
        PRODUCT_ID,
        SUM(QUANTITY) AS LAST_30D_SALES,
        ROUND(SUM(QUANTITY) / 30.0, 2) AS AVG_DAILY_SALES
    FROM ID_POS_TRANSACTIONS
    WHERE TRANSACTION_DATE >= DATEADD('day', -30, CURRENT_DATE())
    GROUP BY STORE_ID, PRODUCT_ID
)
SELECT
    i.INVENTORY_DATE,
    s.STORE_NAME,
    s.PREFECTURE AS STORE_PREFECTURE,
    i.STORE_ID,
    i.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY_LARGE,
    p.MANUFACTURER_NAME,
    i.STOCK_QUANTITY,
    i.REORDER_POINT,
    i.SAFETY_STOCK,
    i.DAYS_OF_SUPPLY,
    i.LAST_REPLENISHMENT_DATE,
    rs.LAST_30D_SALES,
    rs.AVG_DAILY_SALES,
    CASE
        WHEN i.STOCK_QUANTITY = 0 THEN '欠品'
        WHEN i.STOCK_QUANTITY <= i.SAFETY_STOCK THEN '要緊急発注'
        WHEN i.STOCK_QUANTITY <= i.REORDER_POINT THEN '要発注'
        WHEN i.DAYS_OF_SUPPLY > 30 THEN '過剰在庫'
        ELSE '適正'
    END AS STOCK_STATUS
FROM INVENTORY i
JOIN PRODUCT_MASTER p ON i.PRODUCT_ID = p.PRODUCT_ID
JOIN STORE_MASTER s ON i.STORE_ID = s.STORE_ID
LEFT JOIN recent_sales rs
    ON i.STORE_ID = rs.STORE_ID AND i.PRODUCT_ID = rs.PRODUCT_ID;

-- ============================================================
-- 6. カテゴリ別売上トレンド（月次）
-- ============================================================
CREATE OR REPLACE VIEW V_CATEGORY_MONTHLY_TREND AS
SELECT
    DATE_TRUNC('MONTH', t.TRANSACTION_DATE) AS SALES_MONTH,
    p.CATEGORY_LARGE,
    p.CATEGORY_MEDIUM,
    COUNT(DISTINCT t.BASKET_ID)  AS BASKET_COUNT,
    SUM(t.QUANTITY)              AS TOTAL_QUANTITY,
    SUM(t.SALES_AMOUNT)         AS TOTAL_SALES,
    COUNT(DISTINCT t.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    ROUND(SUM(t.SALES_AMOUNT) / NULLIF(COUNT(DISTINCT t.BASKET_ID), 0), 0) AS AVG_BASKET_VALUE
FROM ID_POS_TRANSACTIONS t
JOIN PRODUCT_MASTER p ON t.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    DATE_TRUNC('MONTH', t.TRANSACTION_DATE),
    p.CATEGORY_LARGE,
    p.CATEGORY_MEDIUM;

-- ============================================================
-- 7. メーカー別シェア分析
-- ============================================================
CREATE OR REPLACE VIEW V_MANUFACTURER_SHARE AS
SELECT
    p.CATEGORY_LARGE,
    p.CATEGORY_MEDIUM,
    p.MANUFACTURER_NAME,
    DATE_TRUNC('MONTH', t.TRANSACTION_DATE) AS SALES_MONTH,
    SUM(t.SALES_AMOUNT) AS TOTAL_SALES,
    SUM(t.QUANTITY) AS TOTAL_QUANTITY,
    ROUND(
        SUM(t.SALES_AMOUNT) * 100.0
        / NULLIF(SUM(SUM(t.SALES_AMOUNT)) OVER (
            PARTITION BY p.CATEGORY_LARGE, DATE_TRUNC('MONTH', t.TRANSACTION_DATE)
        ), 0), 2
    ) AS SALES_SHARE_PCT
FROM ID_POS_TRANSACTIONS t
JOIN PRODUCT_MASTER p ON t.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.CATEGORY_LARGE, p.CATEGORY_MEDIUM, p.MANUFACTURER_NAME,
    DATE_TRUNC('MONTH', t.TRANSACTION_DATE);

-- ============================================================
-- 8. 曜日・時間帯別分析
-- ============================================================
CREATE OR REPLACE VIEW V_TIME_ANALYSIS AS
SELECT
    t.DAY_OF_WEEK,
    HOUR(t.TRANSACTION_TIME) AS HOUR_OF_DAY,
    p.CATEGORY_LARGE,
    COUNT(t.TRANSACTION_ID)    AS TRANSACTION_COUNT,
    SUM(t.SALES_AMOUNT)        AS TOTAL_SALES,
    COUNT(DISTINCT t.BASKET_ID) AS BASKET_COUNT
FROM ID_POS_TRANSACTIONS t
JOIN PRODUCT_MASTER p ON t.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    t.DAY_OF_WEEK,
    HOUR(t.TRANSACTION_TIME),
    p.CATEGORY_LARGE;
